use_frameworks!

platform :ios, '9.0'

target 'PodTestXl_Example' do
  pod 'PodTestXl', :path => '../'

  target 'PodTestXl_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
